language: java
sudo: false
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    on_success: never
    on_failure: always
branches:
  only:
    - master
    - testing
    - development
script: 
  - mvn clean cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn --settings .travis.settings.xml deploy